[package]
name = "abstract_db_access"
version = "0.0.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
publish = true

[lib]
name = "abstract_db_access"
path = "src/lib.rs"

[features]
default = []
postgres_tokio = ["dep:tokio-postgres"]
postgres_sqlx = ["dep:sqlx", "sqlx/postgres"]

[dependencies]
tokio-postgres = { version = "0.7.0", default-features = false, optional = true }
sqlx = { version = "0.8.0", default-features = false, optional = true }

[dev-dependencies]
utilities = { path = "../utilities" }

sqlx = { version = "0.8.0", default-features = false, features = [
	"runtime-tokio-rustls",
	"postgres",
	"derive",
	"uuid",
] }
deadpool-postgres = { version = "0.14.1" }
tokio = { version = "1.21.2", features = ["macros", "net"] }
tokio-postgres = { version = "0.7.0", features = ["with-uuid-1"] }

uuid = { version = "1.16.0", features = ["v4", "v7"] }

[[example]]
name = "pg_deadpool"
path = "examples/pg_deadpool.rs"
test = true
required-features = ["postgres_tokio"]

[[example]]
name = "sqlx"
path = "examples/sqlx.rs"
test = true
required-features = ["postgres_sqlx"]
